// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.5
// source: subscription/v1/subscription.proto

package subscriptionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetUserSubscriptionsRequest is the request for GetUserSubscriptions
type GetUserSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSubscriptionsRequest) Reset() {
	*x = GetUserSubscriptionsRequest{}
	mi := &file_subscription_v1_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSubscriptionsRequest) ProtoMessage() {}

func (x *GetUserSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_v1_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*GetUserSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_subscription_v1_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserSubscriptionsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// GetUserSubscriptionsResponse is the response for GetUserSubscriptions
type GetUserSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSubscriptionsResponse) Reset() {
	*x = GetUserSubscriptionsResponse{}
	mi := &file_subscription_v1_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSubscriptionsResponse) ProtoMessage() {}

func (x *GetUserSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_v1_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*GetUserSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_subscription_v1_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserSubscriptionsResponse) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

// Subscription represents a user's subscription to a channel
type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ChannelName   string                 `protobuf:"bytes,3,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_subscription_v1_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_v1_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_subscription_v1_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *Subscription) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Subscription) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *Subscription) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *Subscription) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// GetChannelSubscribersRequest is the request for GetChannelSubscribers
type GetChannelSubscribersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelSubscribersRequest) Reset() {
	*x = GetChannelSubscribersRequest{}
	mi := &file_subscription_v1_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelSubscribersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelSubscribersRequest) ProtoMessage() {}

func (x *GetChannelSubscribersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_v1_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelSubscribersRequest.ProtoReflect.Descriptor instead.
func (*GetChannelSubscribersRequest) Descriptor() ([]byte, []int) {
	return file_subscription_v1_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *GetChannelSubscribersRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

// GetChannelSubscribersResponse is the response for GetChannelSubscribers
type GetChannelSubscribersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelSubscribersResponse) Reset() {
	*x = GetChannelSubscribersResponse{}
	mi := &file_subscription_v1_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelSubscribersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelSubscribersResponse) ProtoMessage() {}

func (x *GetChannelSubscribersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_v1_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelSubscribersResponse.ProtoReflect.Descriptor instead.
func (*GetChannelSubscribersResponse) Descriptor() ([]byte, []int) {
	return file_subscription_v1_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *GetChannelSubscribersResponse) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

var File_subscription_v1_subscription_proto protoreflect.FileDescriptor

const file_subscription_v1_subscription_proto_rawDesc = "" +
	"\n" +
	"\"subscription/v1/subscription.proto\x12\x0fsubscription.v1\"6\n" +
	"\x1bGetUserSubscriptionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"c\n" +
	"\x1cGetUserSubscriptionsResponse\x12C\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x1d.subscription.v1.SubscriptionR\rsubscriptions\"\x86\x01\n" +
	"\fSubscription\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12!\n" +
	"\fchannel_name\x18\x03 \x01(\tR\vchannelName\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\"=\n" +
	"\x1cGetChannelSubscribersRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\":\n" +
	"\x1dGetChannelSubscribersResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds2\x82\x02\n" +
	"\x13SubscriptionService\x12s\n" +
	"\x14GetUserSubscriptions\x12,.subscription.v1.GetUserSubscriptionsRequest\x1a-.subscription.v1.GetUserSubscriptionsResponse\x12v\n" +
	"\x15GetChannelSubscribers\x12-.subscription.v1.GetChannelSubscribersRequest\x1a..subscription.v1.GetChannelSubscribersResponseBGZEgithub.com/Conte777/NewsFlow/pkg/proto/subscription/v1;subscriptionv1b\x06proto3"

var (
	file_subscription_v1_subscription_proto_rawDescOnce sync.Once
	file_subscription_v1_subscription_proto_rawDescData []byte
)

func file_subscription_v1_subscription_proto_rawDescGZIP() []byte {
	file_subscription_v1_subscription_proto_rawDescOnce.Do(func() {
		file_subscription_v1_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscription_v1_subscription_proto_rawDesc), len(file_subscription_v1_subscription_proto_rawDesc)))
	})
	return file_subscription_v1_subscription_proto_rawDescData
}

var file_subscription_v1_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_subscription_v1_subscription_proto_goTypes = []any{
	(*GetUserSubscriptionsRequest)(nil),   // 0: subscription.v1.GetUserSubscriptionsRequest
	(*GetUserSubscriptionsResponse)(nil),  // 1: subscription.v1.GetUserSubscriptionsResponse
	(*Subscription)(nil),                  // 2: subscription.v1.Subscription
	(*GetChannelSubscribersRequest)(nil),  // 3: subscription.v1.GetChannelSubscribersRequest
	(*GetChannelSubscribersResponse)(nil), // 4: subscription.v1.GetChannelSubscribersResponse
}
var file_subscription_v1_subscription_proto_depIdxs = []int32{
	2, // 0: subscription.v1.GetUserSubscriptionsResponse.subscriptions:type_name -> subscription.v1.Subscription
	0, // 1: subscription.v1.SubscriptionService.GetUserSubscriptions:input_type -> subscription.v1.GetUserSubscriptionsRequest
	3, // 2: subscription.v1.SubscriptionService.GetChannelSubscribers:input_type -> subscription.v1.GetChannelSubscribersRequest
	1, // 3: subscription.v1.SubscriptionService.GetUserSubscriptions:output_type -> subscription.v1.GetUserSubscriptionsResponse
	4, // 4: subscription.v1.SubscriptionService.GetChannelSubscribers:output_type -> subscription.v1.GetChannelSubscribersResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_subscription_v1_subscription_proto_init() }
func file_subscription_v1_subscription_proto_init() {
	if File_subscription_v1_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscription_v1_subscription_proto_rawDesc), len(file_subscription_v1_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subscription_v1_subscription_proto_goTypes,
		DependencyIndexes: file_subscription_v1_subscription_proto_depIdxs,
		MessageInfos:      file_subscription_v1_subscription_proto_msgTypes,
	}.Build()
	File_subscription_v1_subscription_proto = out.File
	file_subscription_v1_subscription_proto_goTypes = nil
	file_subscription_v1_subscription_proto_depIdxs = nil
}
