#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- Create users
    CREATE USER ${SUBSCRIPTIONS_DB_USER} WITH PASSWORD '${SUBSCRIPTIONS_DB_PASSWORD}';
    CREATE USER ${NEWS_DB_USER} WITH PASSWORD '${NEWS_DB_PASSWORD}';
    CREATE USER ${ACCOUNTS_DB_USER} WITH PASSWORD '${ACCOUNTS_DB_PASSWORD}';
    CREATE USER ${BOT_DB_USER} WITH PASSWORD '${BOT_DB_PASSWORD}';

    -- Create databases
    CREATE DATABASE subscriptions_db OWNER ${SUBSCRIPTIONS_DB_USER};
    CREATE DATABASE news_db OWNER ${NEWS_DB_USER};
    CREATE DATABASE accounts_db OWNER ${ACCOUNTS_DB_USER};
    CREATE DATABASE bot_db OWNER ${BOT_DB_USER};

    -- Grant privileges
    GRANT ALL PRIVILEGES ON DATABASE subscriptions_db TO ${SUBSCRIPTIONS_DB_USER};
    GRANT ALL PRIVILEGES ON DATABASE news_db TO ${NEWS_DB_USER};
    GRANT ALL PRIVILEGES ON DATABASE accounts_db TO ${ACCOUNTS_DB_USER};
    GRANT ALL PRIVILEGES ON DATABASE bot_db TO ${BOT_DB_USER};

    -- Schema privileges
    \c subscriptions_db
    GRANT ALL ON SCHEMA public TO ${SUBSCRIPTIONS_DB_USER};

    \c news_db
    GRANT ALL ON SCHEMA public TO ${NEWS_DB_USER};

    \c accounts_db
    GRANT ALL ON SCHEMA public TO ${ACCOUNTS_DB_USER};

    \c bot_db
    GRANT ALL ON SCHEMA public TO ${BOT_DB_USER};
EOSQL

echo "Databases and users created successfully!"
